add env variable

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -15,4 +15,14 @@ else
 	exit 1
 fi
 
+HEROKU_WORK_PROCFILE=""
+if [ -f "${ENV_DIR}/HEROKU_WORK_PROCFILE" ]; then
+	HEROKU_WORK_PROCFILE="$(cat "${ENV_DIR}/HEROKU_WORK_PROCFILE")"
+else
+	echo "missing HEROKU_WORK_PROCFILE env variable"
+	exit 1
+fi
+
+
 sed -i "s/HEROKU_WORK_DIRECTIVES/${HEROKU_WORK_DIRECTIVES}/" "${BUILD_DIR}/go.work"
+cp "${HEROKU_WORK_PROCFILE}" "${BUILD_DIR}/"
